### ISSUE TITLE
Problem with git-cz

### ISSUE THREAD

**Issue by Cokaps** [PicGo/bump-version#8]
Hi, there. Thanks for creating such a fantastic project.
I've run into this problem when running yarn cz (it is `"cz":"git-cz`):
```bash
PS D:\GenZOC> yarn cz
'git-cz' is not recognized as an internal or external command,
operable program or batch file.
command not found: git-cz
```
My repo could be found here on [Github](https://github.com/Cokaps/GenZOC)
I'm using [commitlint.config.js](https://github.com/Cokaps/GenZOC/blob/master/commitlint.config.js#L4) and [.husky/commit-msg](https://github.com/Cokaps/GenZOC/blob/master/.husky/commit-msg)

**Comment by Molunerfinn** [comment]
try `npm install -g commitizen git-cz`

**Comment by Cokaps** [comment]
> try `npm install -g commitizen git-cz`

It works. Thanks for your help!!!

**Comment by Cokaps** [comment]
But it then run to another problem, the log is here:
```bash
PS D:\GenZOC> yarn cz
? Select the type of change that you're committing: 🎸  feat:       A new feature
? Write a short, imperative mood description of the change:
  [-------------------------------------------------------------] 55 chars left
   feat: add @PicGo/bump-version
? Provide a longer description of the change:

? List any breaking changes
  BREAKING CHANGE:
? Issues this commit closes, e.g #123:
D:\GenZOC\node_modules\@commitlint\cli\lib\cli.js:112
        throw err;
        ^

Error: Received 'HUSKY_GIT_PARAMS' as value for -E | --env, but environment variable 'HUSKY_GIT_PARAMS' is not available globally
    at getEditValue (D:\GenZOC\node_modules\@commitlint\cli\lib\cli.js:264:19)
    at normalizeFlags (D:\GenZOC\node_modules\@commitlint\cli\lib\cli.js:258:18)
    at main (D:\GenZOC\node_modules\@commitlint\cli\lib\cli.js:140:19)
    at Object.<anonymous> (D:\GenZOC\node_modules\@commitlint\cli\lib\cli.js:107:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
husky - commit-msg hook exited with code 1 (error)
```

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/122628520-0ed92000-d0e9-11eb-9426-8ee0c167ba0d.png)
add this to your package.json
